repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: make
        args: ["black"]
        language: system
    -   id: isort
        name: isort
        entry: make
        args: ["isort"]
        language: system
    -   id: flake8
        name: flake8
        entry: make
        args: ["flake8"]
        language: system
