name: Build Backend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          USERNAME: ${{ secrets.DASHBOARD_USERNAME }}
          PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
          HASHED_PASSWORD: ${{ secrets.DASHBOARD_HASHED_PASSWORD }}
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf ml-models
            git clone https://github.com/lukemiloszewski/ml-models.git
            cd ml-models/backend
            docker-compose -f docker-compose.traefik.yml up --build -d
            docker-compose -f docker-compose.yml up --build -d
