name: Build Backend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
          DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}  # private key
          port: ${{ secrets.PORT }}  # ssh port
          script_stop: true
          envs: BACKEND_URL,DASHBOARD_PASSWORD,DASHBOARD_URL,FRONTEND_URL
          script: |
            rm -rf ml-models
            git clone https://github.com/lukemiloszewski/ml-models.git
            cd ml-models/backend
            export DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD
            export DASHBOARD_HASHED_PASSWORD=$(openssl passwd -apr1 $DASHBOARD_PASSWORD)
            export DASHBOARD_URL=$DASHBOARD_URL
            export FRONTEND_URL=$FRONTEND_URL
            export BACKEND_URL=$BACKEND_URL
            ls -a
            chmod +x /scripts/network.sh
            ./scripts/network.sh
            docker-compose -f docker-compose.traefik.yml up --build -d
            docker-compose -f docker-compose.yml up --build -d
