name: Build Backend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          CORS_ORIGINS: ${{ secrets.CORS_ORIGINS }}
          DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
          DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}  # private key
          port: ${{ secrets.PORT }}  # ssh port
          # fingerprint: ${{ secrets.FINGERPRINT }}
          script_stop: true
          envs: CORS_ORIGINS,DASHBOARD_PASSWORD,DASHBOARD_URL
          script: |
            rm -rf ml-models
            git clone https://github.com/lukemiloszewski/ml-models.git
            cd ml-models/backend
            export CORS_ORIGINS=$CORS_ORIGINS
            export DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD
            export DASHBOARD_HASHED_PASSWORD=$(openssl passwd -apr1 $DASHBOARD_PASSWORD)
            export DASHBOARD_URL=$DASHBOARD_URL
            docker-compose -f docker-compose.traefik.yml up --build -d
            docker-compose -f docker-compose.yml up --build -d
